#!/usr/bin/env python3
"""
Deployment Guide for Streamlit Community Cloud
"""

def print_deployment_guide():
    print("🚀 STREAMLIT COMMUNITY CLOUD DEPLOYMENT GUIDE")
    print("=" * 60)
    
    print("\n📁 STEP 1: PREPARE YOUR FILES")
    print("-" * 50)
    print("✅ app.py - Your main application")
    print("✅ requirements.txt - Python dependencies")
    print("✅ README.md - Project description")
    print("❌ service_account.json - DON'T upload this file!")
    print("   (We'll add it as a secret later)")
    
    print("\n📋 STEP 2: CREATE GITHUB REPOSITORY")
    print("-" * 50)
    print("1. Go to: https://github.com/")
    print("2. Click 'New Repository'")
    print("3. Name it: volunteer-management-app")
    print("4. Make it PUBLIC (required for free tier)")
    print("5. Initialize with README")
    print("6. Create repository")
    
    print("\n📤 STEP 3: UPLOAD YOUR CODE")
    print("-" * 50)
    print("1. Click 'uploading an existing file'")
    print("2. Upload these files:")
    print("   • app.py")
    print("   • requirements.txt")
    print("   • README.md")
    print("3. DON'T upload service_account.json!")
    print("4. Commit the files")
    
    print("\n🚀 STEP 4: DEPLOY TO STREAMLIT")
    print("-" * 50)
    print("1. Go to: https://share.streamlit.io/")
    print("2. Click 'Sign up with GitHub'")
    print("3. Authorize Streamlit")
    print("4. Click 'New app'")
    print("5. Select your repository: volunteer-management-app")
    print("6. Main file path: app.py")
    print("7. Click 'Deploy!'")
    
    print("\n🔐 STEP 5: ADD GOOGLE SHEETS SECRET")
    print("-" * 50)
    print("1. In your Streamlit app dashboard, click 'Settings'")
    print("2. Go to 'Secrets'")
    print("3. Add your service_account.json content like this:")
    print('   [secrets]')
    print('   service_account = """')
    print('   {')
    print('     "type": "service_account",')
    print('     "project_id": "your-project-id",')
    print('     ...')
    print('   }')
    print('   """')
    print("4. Save the secrets")
    
    print("\n🔧 STEP 6: UPDATE YOUR CODE FOR SECRETS")
    print("-" * 50)
    print("You'll need to modify your app.py to use Streamlit secrets:")
    print("Replace the file loading with:")
    print("   import json")
    print("   service_account_info = json.loads(st.secrets['service_account'])")
    print("   creds = ServiceAccountCredentials.from_json_keyfile_dict(service_account_info, scope)")
    
    print("\n✅ STEP 7: TEST YOUR DEPLOYMENT")
    print("-" * 50)
    print("1. Your app will be available at: https://share.streamlit.io/username/repo-name")
    print("2. Test all features")
    print("3. Check Google Sheets integration")
    print("4. Share the URL with others!")
    
    print("\n💡 TROUBLESHOOTING TIPS")
    print("-" * 50)
    print("• App won't start? Check requirements.txt")
    print("• Google Sheets not working? Check secrets format")
    print("• Location not working? HTTPS is required for geolocation")
    print("• Need help? Check Streamlit Community forum")

if __name__ == "__main__":
    print_deployment_guide()
    
    print("\n" + "="*60)
    print("🎯 QUICK CHECKLIST:")
    print("□ Files prepared (app.py, requirements.txt, README.md)")
    print("□ GitHub repository created (PUBLIC)")
    print("□ Code uploaded to GitHub")
    print("□ Streamlit Community Cloud account created")
    print("□ App deployed")
    print("□ Secrets added for Google Sheets")
    print("□ App tested and working")
    print("="*60)
